---
defaultBaseImage: ghcr.io/stuttgart-things/sthings-alpine:1.23
builds:
  - id: run-things
    dir: .
    main: main.go
    ldflags:
      - -s -w -X github.com/stuttgart-things/run-things/internal.version={{.Env.VERSION}}
      - -s -w -X github.com/stuttgart-things/run-things/internal.date={{.Env.BUILD_DATE}}
      - -s -w -X github.com/stuttgart-things/run-things/internal.commit={{.Env.COMMIT}}
